### ISSUE TITLE
Getting None value of l_user = obj_meta.obj_user_meta_list in function: sgie_sink_pad_buffer_probe

### ISSUE THREAD

**Issue by bharat3012** [riotu-lab/deepstream-facenet#10]
Can you tell me the possible reason why I am getting l_user value as None.

**Comment by xya22er** [comment]
Is it always got value none?

**Comment by bharat3012** [comment]
I am using a video in which faces are present in all frames. The method is able to detect them but not recognize. I am getting None in almost all frames, except 2 or 3. Their value is:- <pyds.GList object at 0x7fb4dff7efb8>

**Comment by xya22er** [comment]
Because you enable tracker. If you enable tracker, it will not enter SGIE every time

**Comment by bharat3012** [comment]
Thanks !! Its working Now

**Comment by hirwa145** [comment]
How do i disable the tracker?

**Comment by bharat3012** [comment]
@hirwa145
Two changes:-     
    1. Comment Tracker pipeline
```
    pipeline.add(source)
    pipeline.add(h264parser)
    pipeline.add(decoder)
    pipeline.add(streammux)
    #pipeline.add(tracker)
    pipeline.add(face_detector)
    pipeline.add(face_classifier)
```

2. Change like shown below:-

```
    srcpad.link(sinkpad)
    streammux.link(face_detector)
    #face_detector.link(tracker)
    #tracker.link(face_classifier)
    face_detector.link(face_classifier)
    face_classifier.link(nvvidconv)
```

**Comment by hirwa145** [comment]
I am getting error, `streaming stopped, reason not-linked(-1)`.
