### ISSUE TITLE
This Repo is not updated hence not working

### ISSUE THREAD

**Issue by shubham-shahh** [riotu-lab/deepstream-facenet#5]
Hi, if you are still following this repo use this command instead of the one that is mentioned in the notebook

`python3 -m tf2onnx.convert --input ./facenet_freezed.pb --inputs input_1:0[1,160,160,3] --inputs-as-nchw input_1:0 --outputs Bottleneck_BatchNorm/batchnorm_1/add_1:0 --output facenet.onnx`

as deepstream doesnot accept nhwc format

and even after all the hassle i found [this](https://forums.developer.nvidia.com/t/facenet-with-deepstream-python-not-able-to-parse-output-tensor-meta/159139/19)

please either update the repo with correct code or kindly mention that it is not working

@aniskoubaa I have followed your ROS tutorials and wasn't expecting this from a project in which you are associated.

**Comment by aniskoubaa** [comment]
Hi
Thanks for the feedback The repo is maintained by one of my engineers and to the best I know it has been working as we used it in some projects and it did the work.
**Please specify which deepstream version you have used on which board.**
I have forwarded the message to the repo maintainer to check what you mentioned and reply to you. I did not work particularly on it so I delegate response to my engineers.
Thanks anyway for feedback and I case of an error we will fix inchaAllah 
Thanks

**Comment by shubham-shahh** [comment]
> Hi
> Thanks for the feedback The repo is maintained by one of my engineers and to the best I know it has been working as we used it in some projects and it did the work.
> **Please specify which deepstream version you have used on which board.**
> I have forwarded the message to the repo maintainer to check what you mentioned and reply to you. I did not work particularly on it so I delegate response to my engineers.
> Thanks anyway for feedback and I case of an error we will fix inchaAllah 
> Thanks

Thank you sir for your quick response,
i am using deepstream 5 on Jetson nano board. I can help your team to reproduce the error if they can help me with it.
thank you once again.

**Comment by aniskoubaa** [comment]
Sure they will follow up on this because we are still working and maintaining with this repo for our face recognition application.

**Comment by shubham-shahh** [comment]
> Sure they will follow up on this because we are still working and maintaining with this repo for our face recognition application.

Thank you sir, i am awaiting their response

**Comment by shubham-shahh** [comment]
finally figured out,shall i put up a PR with corrections? @aniskoubaa sir

**Comment by xya22er** [comment]
> Hi, if you are still following this repo use this command instead of the one that is mentioned in the notebook
> 
> `python3 -m tf2onnx.convert --input ./facenet_freezed.pb --inputs input_1:0[1,160,160,3] --inputs-as-nchw input_1:0 --outputs Bottleneck_BatchNorm/batchnorm_1/add_1:0 --output facenet.onnx`
> 
> as deepstream doesnot accept nhwc format
> 
> and even after all the hassle i found [this](https://forums.developer.nvidia.com/t/facenet-with-deepstream-python-not-able-to-parse-output-tensor-meta/159139/19)
> 
> please either update the repo with correct code or kindly mention that it is not working
> 
> @aniskoubaa I have followed your ROS tutorials and wasn't expecting this from a project in which you are associated.
Hi,
Sorry for late. The command line you mentioned it is the same as in reedme file

**Comment by xya22er** [comment]
> > Hi
> > Thanks for the feedback The repo is maintained by one of my engineers and to the best I know it has been working as we used it in some projects and it did the work.
> > **Please specify which deepstream version you have used on which board.**
> > I have forwarded the message to the repo maintainer to check what you mentioned and reply to you. I did not work particularly on it so I delegate response to my engineers.
> > Thanks anyway for feedback and I case of an error we will fix inchaAllah 
> > Thanks
> 
> Thank you sir for your quick response,
> i am using deepstream 5 on Jetson nano board. I can help your team to reproduce the error if they can help me with it.
> thank you once again.

Sorry for late. The command line you mentioned it is the same as in reedme file

**Comment by shubham-shahh** [comment]
> > > Hi
> > > Thanks for the feedback The repo is maintained by one of my engineers and to the best I know it has been working as we used it in some projects and it did the work.
> > > **Please specify which deepstream version you have used on which board.**
> > > I have forwarded the message to the repo maintainer to check what you mentioned and reply to you. I did not work particularly on it so I delegate response to my engineers.
> > > Thanks anyway for feedback and I case of an error we will fix inchaAllah 
> > > Thanks
> > 
> > 
> > Thank you sir for your quick response,
> > i am using deepstream 5 on Jetson nano board. I can help your team to reproduce the error if they can help me with it.
> > thank you once again.
> 
> Sorry for late. The command line you mentioned it is the same as in reedme file

--inputs-as-nchw this flag is not mentioned plus the sgie config file consists of wrong parameters, the nvidia link I shared shows that this implementation works with .onnx file with dynamic batch size this is not mentioned anywhere in this repo plus to get the tensor in python ctypes are to be used no one has mentioned in the repo

**Comment by shubham-shahh** [comment]
> > > Hi
> > > Thanks for the feedback The repo is maintained by one of my engineers and to the best I know it has been working as we used it in some projects and it did the work.
> > > **Please specify which deepstream version you have used on which board.**
> > > I have forwarded the message to the repo maintainer to check what you mentioned and reply to you. I did not work particularly on it so I delegate response to my engineers.
> > > Thanks anyway for feedback and I case of an error we will fix inchaAllah 
> > > Thanks
> > 
> > 
> > Thank you sir for your quick response,
> > i am using deepstream 5 on Jetson nano board. I can help your team to reproduce the error if they can help me with it.
> > thank you once again.
> 
> Sorry for late. The command line you mentioned it is the same as in reedme file

Any Update?

**Comment by AnasMK** [comment]
Hi @shubham-shahh, I'm working on updating the repo with a working version and complete instructions. In couple of days I will update it.

**Comment by shubham-shahh** [comment]
> Hi @shubham-shahh, I'm working on updating the repo with a working version and complete instructions. In couple of days I will update it. 

Meanwhile can you help me to get 128d vector in c++ tensor meta data example? I have configured the app to work with 1 pgie and 1 sgie as facenet and it is working but I am unable to get the 128d vector can you help me with that? @AnasMK

**Comment by shubham-shahh** [comment]
> Hi @shubham-shahh, I'm working on updating the repo with a working version and complete instructions. In couple of days I will update it. 

I can put a pull request as well with a working version.

**Comment by xya22er** [comment]
The repo updated
