### ISSUE TITLE
How to generate .npz files for embeddings?

### ISSUE THREAD

**Issue by bharat3012** [riotu-lab/deepstream-facenet#6]
I am getting the following error:- 

`FileNotFoundError: [Errno 2] No such file or directory: 'embeddings/psu_embeddings_nano_2.npz'`

Let me know how toresolve this issue. Thank you !

**Comment by AnasMK** [comment]
you can find detailed steps to generate `.npz` file in [this link](https://machinelearningmastery.com/how-to-develop-a-face-recognition-system-using-facenet-in-keras-and-an-svm-classifier/)

**Comment by AnasMK** [comment]
Closing issue as no response from author

**Comment by imSrbh** [comment]
How to generate .npz files for embeddings?
@AnasMK
