### ISSUE TITLE
Mismatch between Referenced Embeddings and Deepstream Generated Embeddings for Identical Image

### ISSUE THREAD

**Issue by chanchalkedia** [riotu-lab/deepstream-facenet#7]
I m trying to build Face Recognition for a Single Person. I have generated embeddings.npz from the link you have suggested for my own single class dateset.
I am using your GitHub deepstream_facenet repo, But instead of using KNN classifier, I am calculating eculidean distance between the embeddings.
I have created the video from the same referenced image to calculate the difference in embeddings. And I observed that embeddings generated from referenced image is different from the embeddings i get from deepstream_facenet model.
Also, The distance calculated between Deepstream generated embeddings with the referenced embeddings for the identical Image is around 0.45.
Please suggest where am i going wrong? Do we get different embeddings because of model conversion?

**Comment by xya22er** [comment]
- Did you make normalization before using eculidean distance?

- In the deepstream facenet reedme file:
> Note: you should count avg mean and avg std for your dataset:
Put avg mean in offsets parameter and in the net-scale-factor parameter put (1/avg std) in classifier_config.txt to make facenet model work efficient.

**Comment by LUOQING1994** [comment]
@xya22er 
Hi！
Based on my dataset, I calculated avg mean and avg std of my dataset. I wrote the two values to the classifier_config.txt file,
```
net-scale-factor=0.0262706100252
offsets=127
```
but the program ran wrong.`[UID = 2]: Preprocessor set scale and offsets failed.`

**Comment by xya22er** [comment]
> @xya22er
> Hi！
> Based on my dataset, I calculated avg mean and avg std of my dataset. I wrote the two values to the classifier_config.txt file,
> 
> ```
> net-scale-factor=0.0262706100252
> offsets=127
> ```
> 
> but the program ran wrong.`[UID = 2]: Preprocessor set scale and offsets failed.`

You should write it like this:
offsets=127;127;127

**Comment by LUOQING1994** [comment]
> > @xya22er
> > Hi！
> > Based on my dataset, I calculated avg mean and avg std of my dataset. I wrote the two values to the classifier_config.txt file,
> > ```
> > net-scale-factor=0.0262706100252
> > offsets=127
> > ```
> > 
> > 
> > but the program ran wrong.`[UID = 2]: Preprocessor set scale and offsets failed.`
> 
> You should write it like this:
> offsets=127;127;127

Thank you very much. Now I'm running successfully！

**Comment by hirwa145** [comment]
@LUOQING1994 I need your help, how did you calculate avg std and mean std? What formula did you use to get these values? 
`net-scale-factor=0.0262706100252  offsets=127`? Thank you.

**Comment by imSrbh** [comment]
@hirwa145 @AnasMK @xya22er 
How to generate embeddings for my dataset??
