### ISSUE TITLE
onnx to engine

### ISSUE THREAD

**Issue by LUOQING1994** [riotu-lab/deepstream-facenet#8]
Hi
Thank you very much for your sharing. I have a question and hope to get your help.
In the example code, you directly use the onnx model, but in deepstream, the TRT model is the most efficient way of memory and GPU utilization. So, can you provide a converted TRT model?

**Comment by xya22er** [comment]
This repository will help you
[tf2trt_with_onnx](https://github.com/riotu-lab/tf2trt_with_onnx)
