### ISSUE TITLE
Cannot find function "labels_encoder" in face_utils.py file

### ISSUE THREAD

**Issue by trinhvanson1997** [riotu-lab/deepstream-facenet#9]
Hi, thank for sharing a helpful project about Deepstream.

Can you tell me where can I find function "labels_encoder" in face_utils.py file?

**Comment by xya22er** [comment]
I added It in face_utils.py. Sorry for the mistake

**Comment by trinhvanson1997** [comment]
thank you! but you still miss LabelEncoder class in face_utils.py file. LoL
